export const enum Sprites {
  doorBlue = "door-blue",
  doorCrimson = "door-crimson",
  doorGreenBlue = "door-greenblue",
  doorPlatinum = "door-platinum",
  doorViolet = "door-violet",
  doorYellow = "door-yellow",
  enemy = "enemy-sword",
  enemyBurgeoner = "enemy-hammer",
  enemyFighter = "enemy-sword",
  enemyRanger = "enemy-arrow",
  enemyShadow = "enemy-hidden",
  goldenFeather = "golden-feather",
  item = "item",
  itemBluePotion = "potion-blue",
  itemGuardCard = "card-blue",
  itemGuardDeck = "cards-blue",
  itemLifePotion = "potion-green",
  itemRedPotion = "potion-crimson",
  itemPowerCard = "card-crimson",
  itemPowerDeck = "cards-crimson",
  keyBlue = "key-blue",
  keyCrimson = "key-crimson",
  keyGreenBlue = "key-greenblue",
  keyPlatinum = "key-platinum",
  keyViolet = "key-violet",
  keyYellow = "key-yellow",
  scoreCheck = "score-check",
  scoreCrown = "score-crown",
  scoreStar = "score-star",
  staircaseUp = "staircase-up",
  staircaseDown = "staircase-down",
  startingPosition = "starting-position",
  wall = "wall",
}

export const SPRITES: Sprites[] = [
  Sprites.doorBlue,
  Sprites.doorCrimson,
  Sprites.doorGreenBlue,
  Sprites.doorPlatinum,
  Sprites.doorViolet,
  Sprites.doorYellow,
  Sprites.enemy,
  Sprites.enemyBurgeoner,
  Sprites.enemyFighter,
  Sprites.enemyRanger,
  Sprites.enemyShadow,
  Sprites.goldenFeather,
  Sprites.item,
  Sprites.itemBluePotion,
  Sprites.itemGuardCard,
  Sprites.itemGuardDeck,
  Sprites.itemLifePotion,
  Sprites.itemPowerCard,
  Sprites.itemPowerDeck,
  Sprites.itemRedPotion,
  Sprites.keyBlue,
  Sprites.keyCrimson,
  Sprites.keyGreenBlue,
  Sprites.keyPlatinum,
  Sprites.keyViolet,
  Sprites.keyYellow,
  Sprites.scoreCheck,
  Sprites.scoreCrown,
  Sprites.scoreStar,
  Sprites.staircaseUp,
  Sprites.staircaseDown,
  Sprites.startingPosition,
  Sprites.wall,
]
