export const enum Sprites {
  doorBlue = "door-blue",
  doorCrimson = "door-crimson",
  doorGreenBlue = "door-greenblue",
  doorPlatinum = "door-platinum",
  doorViolet = "door-violet",
  doorYellow = "door-yellow",

  enemyBurgeoner = "enemy-hammer",
  enemyFighter = "enemy-sword",
  enemyRanger = "enemy-arrow",
  enemyShadow = "enemy-hidden",
  enemySlasher = "enemy-knife",

  itemGoldenFeather = "item-golden-feather",
  item = "item",
  itemBluePotion = "item-potion-blue",
  itemGuardCard = "item-card-blue",
  itemGuardDeck = "item-cards-blue",
  itemGuardGem = "item-gem-blue",
  itemGuardPiece = "item-piece-blue",
  itemGuardPotion = "item-jug-blue",
  itemHeavenlyPotion = "item-potion-yellow",
  itemLifePotion = "item-potion-green",
  itemRedPotion = "item-potion-crimson",
  itemPowerCard = "item-card-crimson",
  itemPowerDeck = "item-cards-crimson",
  itemPowerGem = "item-gem-crimson",
  itemPowerPiece = "item-piece-crimson",
  itemPowerPotion = "item-jug-crimson",

  keyBlue = "key-blue",
  keyCrimson = "key-crimson",
  keyGreenBlue = "key-greenblue",
  keyPlatinum = "key-platinum",
  keyViolet = "key-violet",
  keyYellow = "key-yellow",
  scoreCheck = "score-check",
  scoreCrown = "score-crown",
  scoreStar = "score-star",
  staircaseUp = "staircase-up",
  staircaseDown = "staircase-down",
  startingPosition = "starting-position",
  wall = "wall",
}

export const SPRITES: Sprites[] = [
  Sprites.doorBlue,
  Sprites.doorCrimson,
  Sprites.doorGreenBlue,
  Sprites.doorPlatinum,
  Sprites.doorViolet,
  Sprites.doorYellow,

  Sprites.enemyBurgeoner,
  Sprites.enemyFighter,
  Sprites.enemyRanger,
  Sprites.enemyShadow,
  Sprites.enemySlasher,

  Sprites.item,
  Sprites.itemGoldenFeather,
  Sprites.itemBluePotion,
  Sprites.itemGuardCard,
  Sprites.itemGuardDeck,
  Sprites.itemGuardGem,
  Sprites.itemGuardPiece,
  Sprites.itemGuardPotion,
  Sprites.itemHeavenlyPotion,
  Sprites.itemLifePotion,
  Sprites.itemPowerCard,
  Sprites.itemPowerDeck,
  Sprites.itemPowerGem,
  Sprites.itemPowerPiece,
  Sprites.itemPowerPotion,
  Sprites.itemRedPotion,

  Sprites.keyBlue,
  Sprites.keyCrimson,
  Sprites.keyGreenBlue,
  Sprites.keyPlatinum,
  Sprites.keyViolet,
  Sprites.keyYellow,
  Sprites.scoreCheck,
  Sprites.scoreCrown,
  Sprites.scoreStar,
  Sprites.staircaseUp,
  Sprites.staircaseDown,
  Sprites.startingPosition,
  Sprites.wall,
]
