export const enum Sprites {
  doorBlue = "door-blue",
  doorCrimson = "door-crimson",
  doorGreenBlue = "door-greenBlue",
  doorPlatinum = "door-platinum",
  doorViolet = "door-violet",
  doorYellow = "door-yellow",
  enemy = "enemy",
  item = "item",
  keyBlue = "key-blue",
  keyCrimson = "key-crimson",
  keyGreenBlue = "key-greenBlue",
  keyPlatinum = "key-platinum",
  keyViolet = "key-violet",
  keyYellow = "key-yellow",
  staircaseUp = "staircase-up",
  staircaseDown = "staircase-down",
  startingPosition = "starting-position",
  wall = "wall",
}

export const SPRITES: Sprites[] = [
  Sprites.doorBlue,
  Sprites.doorCrimson,
  Sprites.doorGreenBlue,
  Sprites.doorPlatinum,
  Sprites.doorViolet,
  Sprites.doorYellow,
  Sprites.enemy,
  Sprites.item,
  Sprites.keyBlue,
  Sprites.keyCrimson,
  Sprites.keyGreenBlue,
  Sprites.keyPlatinum,
  Sprites.keyViolet,
  Sprites.keyYellow,
  Sprites.staircaseUp,
  Sprites.staircaseDown,
  Sprites.startingPosition,
  Sprites.wall,
]
